language: R
env:
  global:
    secure: g8ij+38N/bOZ5A33KeQmkumEQj4nHJisNpIAzyt23J0MZPeEocMIM4h3+6eyA/87FI7Q86Y+nr4BloswHiDToQaMrL9So8NAevAL3ZRQCRGTjRGs5a7VAl3AkVgqWi/ouyS2IGoIycyLuutqcWmur+uUMRHCwjNjpKzbWcKupee9sClB0K7jKwoNpmbmvWNLR9oLEeu0YWnPUoW8f7vtGsGZyoBUoiwMqVP824KqPChZ7OznK7J4hs23Fv7F56LtJa7eCFrjDaUqBCeIB2oEWc5Lcb0D2kMOBkzoD/IXMwyGYITlP0m60ao6TOFjiHvOHE+xaprbAxojI5Ev2GKB212oCBM+Z7ey1tsVW3YtVwzk+YuxvQTUIPzRaA4k2n0+jMzj8kcfJ4kR8dWECgPGBAmF/z7k/0wkUc4UkOQ/YgW/r186GBtmCVADA+HuMRL4ROT+sm7oq31WhL5C2ORUWirIG8hMUDca9+1D3CWtvcd9xzVrqZCyQIOl2+Asjr+k6/QPCcNvzxGLH/ibvZXJgQfP2VP0+RH92Muyx4PYLv9ICh0VXNjbh3vZEGuSzaTYoK5bg49oD6CQUvtFDlhwIpTLz2/0WXL326R3fPGIrWxSFQhIhq6HnX4WWQ7z1rc/gwxM46gO5eb0Dget9GTHbhN6fqcVE9XSVm8cKWIt7Es=
matrix:
  include:
  - os: linux
    r: release
  - os: osx
    r: release
if: tag IS blank
sudo: false
cache: packages
notifications:
  email:
    on_success: change
    on_failure: change
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then R -e 'source("https://install-github.me/r-lib/remotes")'; fi
after_success:
  # Get Package name and version from DESCRIPTION
  - 'export PKGVER=$(sed -n "s/Version: *\([^ ]*\)/\1/p" DESCRIPTION)'
  - 'export PKGNAME=$(sed -n "s/Package: *\([^ ]*\)/\1/p" DESCRIPTION)'
  - 'export SRC_PKG_FILE=${PKGNAME}_${PKGVER}'
  - "echo $SRC_PKG_FILE"
  # Build binary and remove the source archive
  - "R CMD INSTALL --build ${SRC_PKG_FILE}.tar.gz"
  - "rm ${SRC_PKG_FILE}.tar.gz"
  # Look for binary bundle (*.tgz for OSX and *.tar.gz for Linux)
  - "export BIN_PKG_FILE=$(ls $PKGNAME*gz)"
  - "echo Resulting binary: $BIN_PKG_FILE"
before_deploy:
  # Set up git user name and tag this commit
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export TRAVIS_TAG=$PKGNAME-v$PKGVER
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key:
    secure: OS/5d3aij+1HI+enQud9dJoIiEF3C5hBCO/XmxE50sJ2swUlcHQAM4Radb1/LQgIgRm9Zz1cuUV/Ch7sgRDJzFf69U0IO08S6wb0f/xZZo0X0HZzG8YMGz+lD4PGmgt9kqWyWswih6e3vdF6rJQGotBqV+yvu+hb/vnrbSIsTL9YFhM3ueCY8SKysYkEYtuK5NnTUXXa2dXpnJBaIl16EXT5OJTSzngjlGpw0+2JfgUmgRvRYVNnTkrCGVRjAOZ+UQdgX1UwbQggJ06xXr315TurOEcnbesuerZW7ovRtzJswmJhZGJozzFbQtY6T3RUjM1jC7sZCERt9ZoxXzDC1vK+oBk3nC1VelJXIFyONeu14UNE+AlswJhI31+GxL4dXwW9O5jXBzBeMArpgjaHYVdi3ZsB+a43ti+H7bNyJVrgHACGIzUNFZkXsuLRMQkC7PQhf6iPtW/z9pWp8WVgJVw9BLcz1MNLHgEEg19sKSxWrbRg0CamSR7QrZqUVWytBWhBY/uGvAiDC1Qjl7+fUF+OLC44sT+AxU4bVrykdrTlmuy9FICs7jlW8rBQiQV9fSetLsBnxAC9J2jT1quF3G+Nd704IwUVrWB+YqD2kc5F1ErPw39qGgGtjka4IUVeEVVLSnVGueZyj3nJ+qoSjLlkFjhpE57/9OpkPFUpoV8=
  file: $BIN_PKG_FILE
  skip_cleanup: true
  on:
    branch: master
